server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: client-app
            client-secret: secret
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/custom"
            client-name: CustomClient
        provider:
          custom:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9000/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9000/oauth2/jwks
