spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: client-app
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/custom
            scope: openid,profile,email
        provider:
          custom:
            issuer-uri: http://localhost:9000
server:
  port: 8082
  servlet:
    session:
      cookie:
        same-site: none
        secure: false
