spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: client-app
            client-secret: client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/custom"
            scope: openid, profile, email
        provider:
          custom:
            issuer-uri: http://localhost:9000



server:
  port: 8082

logging:
    level:
      org.springframework.security: DEBUG
